function [theta, accept] = Mit_MH(N, kernel, mit, GamMat)
% perform independence MH sampling using mixture of t densities as the
% candidate density
% input:
% N - lenght of the generated chain
% kernel - function which computes the kernel
% mit - mixture of t's
% output:
% theta - [Nxk] matrix of samples generated by the independence MH
% accept - acceptance rate in the independence MH

    resampl_on = false;
   
    [theta, lnk, ~] = fn_rmvgt_robust(N, mit, kernel, resampl_on);
    ind_real = ((imag(lnk)==0) & ~isnan(lnk));
    lnk(~ind_real) = -Inf;
    
    lnd = dmvgt(theta, mit, true, GamMat);
%     norm = false;
%     lnw = fn_ISwgts(lnk, lnd, norm);
%     lnw = log(lnw); %log weights 
    lnw = lnk - lnd;
    lnw = lnw - max(lnw);
       
    [ind, a] = fn_MH(lnw);
    theta = theta(ind,:);
    accept = a/N;
end